### ISSUE TITLE
FONTOS FELADAT

### ISSUE THREAD

**Issue by herbakmarcell** [herbakmarcell/afp2_saturn#162]
Kommentekben ki van fejtve a feladat.

**Comment by herbakmarcell** [comment]
Boldog Születésnapot Tomi! 😄

**Comment by FourthRuffle** [comment]
Boldog születésnapot! ❤️  🥇 💯

**Comment by Juuhva** [comment]
Boldog születésnapot Tommer! 🎂

**Comment by gyorkistamas** [comment]
Köszi szépen srácok 🤣 🤣
